services:
  backend-flask: 
    build:
      context: backend-flask
      target: development
    # flask requires SIGINT to stop gracefully
    # (default stop signal from Compose is SIGTERM)
    stop_signal: SIGINT
    ports:
      - '8000:8000'
    x-develop:
      watch:
        - action: rebuild
          path: ./backend-flask
    environment:
    # change set these in deployment
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db

  backend-django:
    build:
      context: backend-django
      target: development
    ports:
      - '8000:8000'
    x-develop:
      watch:
        - action: rebuild
          path: ./backend-django
    environment:
    # change set these in deployment
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db

  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      # change set these in deployment
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432